language: node_js

node_js:
  - "stable"
  - "lts/*"

cache:
  directories:
  - node_modules
git:
  depth: 3

script:
  - gatsby build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  target-branch: master
  verbose: true
  on:
    branch: master-source
